import './globals.css'

import { Inter } from 'next/font/google'
import { ptBR } from '@clerk/localizations'
import { neobrutalism } from '@clerk/themes'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
      localization={ptBR}
      appearance={{
        baseTheme: neobrutalism,
        elements: { formButtonPrimary: 'bg-violet-500 hover:bg-violet-600' }
      }}
    >
      <html lang="en">
        <head>
          <title>Auth Clerk</title>
        </head>
        <body className={inter.className}>
          <div className="h-screen flex justify-center items-center">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
